export const LOAD_TODOS_STARTED = 'LOAD_TODOS_STARTED';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';

export const ADD_NEW_TODO_STARTED = 'ADD_NEW_TODO_STARTED';
export const ADD_NEW_TODO_SUCCESS = 'ADD_NEW_TODO_SUCCESS';
export const ADD_NEW_TODO_FAILURE = 'ADD_NEW_TODO_FAILURE';

export const TOGGLE_TODO_DONE_STARTED = 'TOGGLE_TODO_DONE_STARTED';
export const TOGGLE_TODO_DONE_SUCCESS = 'TOGGLE_TODO_DONE_SUCCESS';
export const TOGGLE_TODO_DONE_FAILED = 'TOGGLE_TODO_DONE_FAILED';

export const DELETE_TODO_STARTED = 'DELTE_TODO_STARTED';
export const DELETE_TODO_SUCCESS = 'DELTE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELTE_TODO_FAILED';

export const URL = 'https://localhost:5001/';